### ISSUE TITLE
Shield.io 속도 문제

### ISSUE THREAD

**Issue by ryush00** [markquery/spidersweb#4]
데모 사이트 너무 로드 속도가 느려서 확인해 보았더니 Shield.io 로드가 너무 오래 걸리는 듯 합니다.. 아니, 로드가 안됩니다.

![image](https://cloud.githubusercontent.com/assets/4997174/8877464/96678652-3260-11e5-99c4-5c5a1d9b5a82.png)

**Comment by ungki** [comment]
최근 shield.io의 문제가 있는 듯합니다. 사용하실 때는 삭제하시기 바랍니다. 감사합니다!

**Comment by ungki** [comment]
https://github.com/markquery/spidersweb/commit/516f328ddf5cf46f25bcd09c2449f6a9cd74911b

**Comment by ryush00** [comment]
감사합니다!
:+1:
